FROM mcr.microsoft.com/mssql/server:2022-latest

USER root

COPY ./scripts/ /scripts

COPY ./init-db.sh init-db.sh
RUN chmod +x init-db.sh

COPY ./entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

EXPOSE 1435

USER mssql
CMD /bin/bash entrypoint.sh
